version: '3.9'

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: javadb
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
